"use server";

import { randomUUID } from "node:crypto";
import { redirect } from "next/navigation";
import { ApiError, publicApi } from "@/lib/api";
import type { AppointmentCreated } from "@/lib/types";

/**
 * A customer taking a slot.
 *
 * <p>A server action rather than a fetch from the browser, like every write in
 * this application: the form posts here, this calls the API, and no token, no
 * base URL and no request shape is ever visible to a page. It also means the
 * booking works with JavaScript switched off, which on a phone in Conakry is
 * not a hypothetical.
 *
 * <p>The idempotency key is minted here, once per submission. The contract
 * requires one because a retried booking burns a slot nobody can use - and a
 * key generated in the browser would be regenerated by a reload, which is
 * exactly the case it exists for.
 */
export async function book(formData: FormData): Promise<void> {
  const slug = String(formData.get("slug"));
  const staffId = String(formData.get("staff_id") ?? "");

  let created: AppointmentCreated;
  try {
    created = await publicApi<AppointmentCreated>(
      `/v1/providers/${encodeURIComponent(slug)}/appointments`,
      {
        method: "POST",
        idempotencyKey: randomUUID(),
        body: {
          service_offering_id: String(formData.get("service_offering_id")),
          // Omitted and never null: the contract says omit to let the server
          // pick, and a null would be a client asking for nobody in particular
          // in a field that means somebody in particular.
          ...(staffId ? { staff_id: staffId } : {}),
          starts_at: String(formData.get("starts_at")),
          customer: {
            full_name: String(formData.get("full_name")),
            phone: String(formData.get("phone")),
          },
          ...(formData.get("customer_note")
            ? { customer_note: String(formData.get("customer_note")) }
            : {}),
        },
      },
    );
  } catch (error) {
    if (error instanceof ApiError) {
      redirect(`/p/${slug}?error=${error.code ?? "UNKNOWN"}`);
    }
    throw error;
  }

  // The reference is the only handle a customer without an account has. It goes
  // in the URL they land on, so it is in their history and their address bar
  // before any message arrives.
  redirect(`/bookings/${created.reference}`);
}
