"use server";

import { randomUUID } from "node:crypto";
import { redirect } from "next/navigation";
import { ApiError, publicApi } from "@/lib/api";
import type { AppointmentCreated, ServiceAddress } from "@/lib/types";

/**
 * A customer taking a slot.
 *
 * <p>A server action rather than a fetch from the browser, like every write in
 * this application: the form posts here, this calls the API, and no token, no
 * base URL and no request shape is ever visible to a page. It also means the
 * booking works with JavaScript switched off, which on a phone in Conakry is
 * not a hypothetical.
 */
export async function book(formData: FormData): Promise<void> {
  const slug = text(formData, "slug");
  const serviceId = text(formData, "service_offering_id");
  const staffId = text(formData, "staff_id");
  const date = text(formData, "date");
  const note = text(formData, "customer_note");
  const email = text(formData, "email");
  const channel = text(formData, "preferred_channel");
  const address = addressFrom(formData);

  let created: AppointmentCreated;
  try {
    created = await publicApi<AppointmentCreated>(
      `/v1/providers/${encodeURIComponent(slug)}/appointments`,
      {
        method: "POST",
        // Minted here, once per submission, and never in the browser: a key
        // generated on the page would be regenerated by a reload, which is
        // precisely the case the header exists to cover. The contract requires
        // one because a retried booking otherwise burns a slot nobody can use.
        idempotencyKey: randomUUID(),
        // No provider identifier anywhere in this body. The tenant is the slug
        // in the path, and it is the only place the contract puts it.
        body: {
          service_offering_id: serviceId,
          // Omitted, never null. The contract reads a null as "nobody in
          // particular" in a field that means somebody in particular, and the
          // two are different promises: ask for one person and the answer when
          // their slot goes is that it is gone, not that a colleague will do.
          ...(staffId ? { staff_id: staffId } : {}),
          // Already a UTC instant: it is the value listAvailableSlots minted,
          // carried through the radio unchanged. Nothing here reads a wall
          // clock, so there is nothing here to convert.
          starts_at: text(formData, "starts_at"),
          customer: {
            full_name: text(formData, "full_name"),
            phone: text(formData, "phone"),
            // Sent whenever it was typed, whatever the choice: the island
            // hides that field, it does not remove it, so a customer who
            // filled it in and then picked WhatsApp still posts an address.
            // Keeping it is the kinder read - it is what reaches them if the
            // appointment is cancelled a month later - and the contract makes
            // it optional for exactly that.
            ...(email ? { email } : {}),
            // Absent means WhatsApp, which is what every booking made before
            // this question existed already meant, so an empty field is
            // omitted rather than filled in here. A value that is neither of
            // the two is passed on untouched: a client that quietly corrected
            // a tampered body would be answering for the customer, and the
            // API's own refusal is the honest answer.
            ...(channel ? { preferred_channel: channel } : {}),
          },
          // Present only on a call-out. The contract refuses an address on a
          // service performed at the shop, and it is right to: an appointment
          // at the salon that carried somebody's home address would be storing
          // it for nothing.
          ...(address ? { service_address: address } : {}),
          ...(note ? { customer_note: note } : {}),
        },
      },
    );
  } catch (error) {
    // A refusal is an answer, not a fault. Uncaught, an ApiError renders the
    // 500 page, which tells a customer the product is broken when the server
    // merely said no - and the one thing it said no about, a slot taken a
    // second ago, is the likeliest thing to happen on a busy Saturday.
    //
    // The selections go back into the URL so the customer lands on the same
    // step with the same service and the same week. The name, the telephone
    // and the address do not: they are the customer's own details and a query
    // string is written into history, into the address bar and into every log
    // along the way. Retyping where you live is cheaper than publishing it.
    if (error instanceof ApiError) {
      redirect(refusalUrl(slug, serviceId, staffId, date, error.code));
    }
    throw error;
  }

  // The reference is the only handle a customer without an account has, so it
  // goes in the URL they land on - in their history and their address bar
  // before any confirmation message arrives.
  redirect(`/bookings/${encodeURIComponent(created.reference)}`);
}

/**
 * Where to come, or nothing at all.
 *
 * <p>The block is rendered only for a call-out, so an empty `directions` means
 * the form never asked - and the address is then omitted whole rather than
 * sent hollow. A commune and a quartier with no way to find the door would be
 * refused anyway, and would be useless to the tradesman if they were not.
 */
function addressFrom(formData: FormData): ServiceAddress | null {
  const directions = text(formData, "directions");
  if (!directions) return null;
  const localitySlug = text(formData, "locality_slug");
  const area = text(formData, "area");
  return {
    ...(localitySlug ? { locality_slug: localitySlug } : {}),
    ...(area ? { area } : {}),
    directions,
  };
}

/** Back to the third step, as the customer left it, with the reason attached. */
function refusalUrl(
  slug: string,
  serviceId: string,
  staffId: string,
  date: string,
  code: string | null,
): string {
  const query = new URLSearchParams({ etape: "3", service: serviceId });
  if (staffId) query.set("staff", staffId);
  if (date) query.set("date", date);
  query.set("error", code ?? "UNKNOWN");
  return `/p/${encodeURIComponent(slug)}/reserver?${query.toString()}`;
}

/** A field as the form sent it: a string, trimmed, or empty when absent. */
function text(formData: FormData, name: string): string {
  const value = formData.get(name);
  return typeof value === "string" ? value.trim() : "";
}
